### ISSUE TITLE
Статья по Optional

### ISSUE THREAD

**Issue by aarexer** [qcha/JBook#2]
С выходом Java 8 появился механизм, который позволяет более удобно работать с полями, которые могут содержать null.

Этому стоит посвятить целую статью, на мой взгляд

**Comment by Lupen2002** [comment]
Кое что накидал. @aarexer глянь норм не норм, вторую часть чуть позже.

**Comment by aarexer** [comment]
Готово:
https://github.com/qcha/JBook/blob/master/start/optional.md
