### ISSUE TITLE
Правки по HTTP 1.1

### ISSUE THREAD

**Issue by aarexer** [qcha/JBook#202]
- Исправления по опечаткам, замечаниям
- ToC

**Comment by vladislavvv** [comment]
Документ получился достаточно внушительным. Что думаешь насчет добавления TOC в него?

**Comment by aarexer** [comment]
Добавлю к тому что надо сделать

**Comment by vladislavvv** [comment]
<img src="https://github.com/qcha/JBook/assets/12036688/b3f9edf5-f4ba-485a-bbdd-54a7787c0373" width="400">

Пример с content-type не обернут в кавычки как пример с content-length

**Comment by vladislavvv** [comment]
[В разделе про Cache-Control](https://github.com/qcha/JBook/blob/master/other/http/http_11.md#cache-control)

<img width="1018" alt="image" src="https://github.com/qcha/JBook/assets/12036688/67e7bfd3-bdea-444a-ad2f-b8627142a82f">

**Comment by vladislavvv** [comment]
Там же

<img width="782" alt="image" src="https://github.com/qcha/JBook/assets/12036688/c01c3bd4-9cb5-4850-a905-c78e1f3a60d0">

**Comment by vladislavvv** [comment]
<img width="1031" alt="image" src="https://github.com/qcha/JBook/assets/12036688/44f1e9d0-c0e7-4e01-a414-0913c4e9cc82">

**Comment by vladislavvv** [comment]
В разделе [кешируемость](https://github.com/qcha/JBook/blob/master/other/http/http_11.md#%D0%BA%D0%B5%D1%88%D0%B8%D1%80%D1%83%D0%B5%D0%BC%D0%BE%D1%81%D1%82%D1%8C)

> При этом снижать кеширование может быть на разных этапах: как ближе к клиенту (на прокси, например), так и ближе к серверу (на gateway-е).

Не очень понял, что ты имел в виду, может переписать это предложение?

Например, если я правильно угадал смысл
> При этом применять кеширование можно на разных этапах: как ближе к клиенту (на прокси, например), так и ближе к серверу (на gateway-е).

**Comment by dzubenco** [comment]
Привет. Тут ошибка в окончании (поменять на «отправки»), это в пункте «как отправлять запросы»
![IMG_1878](https://github.com/qcha/JBook/assets/74211642/427b0109-798c-4e36-8236-bfd5a16743a9)

**Comment by sleepdan** [comment]
1.
![image](https://github.com/qcha/JBook/assets/37826094/ba8e24e6-5a82-4bf8-9cfa-b83e6ad2f34e)
Если я правильно понял, то в тексте написано что PATCH "Может как быть идемпотентным, так и не быть", но в таблице в столбце про PATCH утверждается что он "Не идемпотентный" - что на мой взгляд вызывает противоречие.

2. 
![image](https://github.com/qcha/JBook/assets/37826094/ccb56f50-ada4-4ccc-ad20-47c9cdc061d6)
"Обработку"?

3.
![image](https://github.com/qcha/JBook/assets/37826094/5f9e109d-0629-4dbb-832e-bb6b5dd8bf1d)

4.
![image](https://github.com/qcha/JBook/assets/37826094/78635a2c-0139-4349-bd6e-71eed6cf0a5e)
