### ISSUE TITLE
Сортировка пузырьком

### ISSUE THREAD

**Issue by JannaMelnikova** [qcha/JBook#279]

**Comment by aarexer** [comment]
Привет!
Про это описал: https://github.com/qcha/JBook/blob/master/algorithms/sorting/bubble.md

Можем закрывать issue? Или есть дополнения по нему?

**Comment by aarexer** [comment]
В общем, закрою обращение, в связи с тем, что уже выполнено. Если было сложно найти,  проблемы со структурой и навигацией - создайте issue новое с описанием что и как, либо можно написать мне лично и рассказать о проблеме!
