### ISSUE TITLE
Поведенческие шаблоны

### ISSUE THREAD

**Issue by aarexer** [qcha/JBook#36]
Command (Команда);
Interpreter (Интерпретатор);
Iterator (Итератор);
Mediator (Посредник);
Memento (Хранитель);
Observer (Наблюдатель);
State (Состояние);
Strategy (Стратегия);
Template method (Шаблонный метод);
Visitor (Посетитель).

**Comment by ilya144** [comment]
Chain of responsibility (Цепочка обязанностей) нужен?

**Comment by aarexer** [comment]
Да, думаю да
Я просто накидал что вспомнил в описание
