### ISSUE TITLE
Аннотации

### ISSUE THREAD

**Issue by aarexer** [qcha/JBook#38]
Зачем
Что
Почему
Как

Все имеет свой рантайм, даже C - просто у него рантайм маленький и может разве что выделять память и очищать
В Java и JVM рантайм большой - аннотации и рефлексия

**Comment by cac03** [comment]
О, тут, оказывается, было issue на аннотации.
@aarexer , ты сказал, что немножко поправишь статью, тогда и issue, наверное, можно будет закрыть)
