### ISSUE TITLE
Опечатки в топике про final

### ISSUE THREAD

**Issue by grobert608** [qcha/JBook#90]
Привет!
В примере [про классы](https://github.com/qcha/JBook/blob/master/start/final.md#%D0%B7%D0%B0%D0%B2%D0%B5%D1%80%D1%88%D0%B5%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%B0) отсутсвует ключевое слово `class` у `FileUtils`.
В примере [про методы](https://github.com/qcha/JBook/blob/master/start/final.md#%D0%B7%D0%B0%D0%B2%D0%B5%D1%80%D1%88%D0%B5%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D0%B0) отсутсвуют ключевые слова `class` у `Person` и `final` у метода.
В [примере](https://github.com/qcha/JBook/blob/master/start/final.md#%D1%81%D0%B2%D0%BE%D0%B9%D1%81%D1%82%D0%B2%D0%BE-%D0%BA%D0%BB%D0%B0%D1%81%D1%81%D0%B0) отсутсвует ключевое слово `class` у `ArrayList `.

**Comment by aarexer** [comment]
Большое спасибо!
Исправлено!

**Comment by grobert608** [comment]
В примере [про методы](https://github.com/qcha/JBook/blob/master/start/final.md#%D0%B7%D0%B0%D0%B2%D0%B5%D1%80%D1%88%D0%B5%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D0%B0) отсутсвует ключевое слово final у метода.
