### ISSUE TITLE
Опечатки в топике про final (2)

### ISSUE THREAD

**Issue by grobert608** [qcha/JBook#91]
Привет!
В примере [про методы](https://github.com/qcha/JBook/blob/master/start/final.md#%D0%B7%D0%B0%D0%B2%D0%B5%D1%80%D1%88%D0%B5%D0%BD%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D0%B0) все еще отсутсвует ключевое слово final у метода.
`final void hello() {}`

**Comment by aarexer** [comment]
Done!
Thanx!
